const { WsProvider } = require('@polkadot/api')
export const PROVIDER = new WsProvider('wss://kusama-rpc.polkadot.io/')
export const INDEXER = 'https://kusama.indexer.gc.subsquid.io/v4/graphql'
export const API_RETRIES = 5;
export const QUERY_CACHE_SIZE = 100

export const EXTRINISIC_WHITE_LIST = new Map([
        ["auctions.bid" , true],
        ["balances.transfer" , true],
        ["balances.transferKeepAlive" , true],
        ["bounties.acceptCurator" , true],
        ["bounties.claimBounty" , true],
        ["bounties.extendBountyExpiry" , true],
        ["claims.claim" , true],
        ["council.close" , true],
        ["council.propose" , true],
        ["council.vote" , true],
        ["crowdloan.addMemo" , true],
        ["crowdloan.contribute" , true],
        ["crowdloan.create" , true],
        ["crowdloan.poke" , true],
        ["crowdloan.withdraw" , true],
        ["democracy.cancelReferendum" , true],
        ["democracy.delegate" , true],
        ["democracy.fastTrack" , true],
        ["democracy.noteImminentPreimage" , true],
        ["democracy.notePreimage" , true],
        ["democracy.propose" , true],
        ["democracy.removeVote" , true],
        ["democracy.second" , true],
        ["democracy.undelegate" , true],
        ["democracy.unlock" , true],
        ["democracy.vote" , true],
        ["electionProviderMultiPhase.submitUnsigned" , true],
        ["electionsPhragmen.removeVoter" , true],
        ["electionsPhragmen.submitCandidacy" , true],
        ["electionsPhragmen.vote" , true],
        ["gilt.placeBid" , true],
        ["gilt.retractBid" , true],
        ["identity.addRegistrar" , true],
        ["identity.addSub" , true],
        ["identity.cancelRequest" , true],
        ["identity.clearIdentity" , true],
        ["identity.killIdentity" , true],
        ["identity.provideJudgement" , true],
        ["identity.removeSub" , true],
        ["identity.renameSub" , true],
        ["identity.requestJudgement" , true],
        ["identity.setFee" , true],
        ["identity.setIdentity" , true],
        ["identity.setSubs" , true],
        // ["imOnline.heartbeat" , true],
        ["indices.claim" , true],
        ["indices.free" , true],
        ["multisig.approveAsMulti" , true],
        ["multisig.asMulti" , true],
        ["multisig.cancelAsMulti" , true],
        ["parasInherent.enter" , true],
        ["phragmenElection.removeVoter" , true],
        ["phragmenElection.submitCandidacy" , true],
        ["phragmenElection.vote" , true],
        ["proxy.addProxy" , true],
        ["proxy.announce" , true],
        ["proxy.anonymous" , true],
        ["proxy.proxy" , true],
        ["proxy.proxyAnnounced" , true],
        ["proxy.removeAnnouncement" , true],
        ["proxy.removeProxies" , true],
        ["proxy.removeProxy" , true],
        ["recovery.createRecovery" , true],
        ["recovery.initiateRecovery" , true],
        ["registrar.deregister" , true],
        ["registrar.register" , true],
        ["registrar.reserve" , true],
        ["session.purgeKeys" , true],
        ["session.setKeys" , true],
        ["slots.triggerOnboard" , true],
        ["society.bid" , true],
        ["society.defenderVote" , true],
        ["society.payout" , true],
        ["society.setMaxMembers" , true],
        ["society.unbid" , true],
        ["society.vote" , true],
        ["society.vouch" , true],
        ["staking.bond" , true],
        ["staking.bondExtra" , true],
        ["staking.chill" , true],
        ["staking.kick" , true],
        ["staking.nominate" , true],
        ["staking.payoutStakers" , true],
        ["staking.rebond" , true],
        ["staking.setController" , true],
        ["staking.setPayee" , true],
        ["staking.submitElectionSolutionUnsigned" , true],
        ["staking.unbond" , true],
        ["staking.validate" , true],
        ["staking.withdrawUnbonded" , true],
        ["system.remark" , true],
        ["technicalCommittee.close" , true],
        ["technicalCommittee.propose" , true],
        ["technicalCommittee.vote" , true],
        // ["timestamp.set" , true],
        ["tips.closeTip" , true],
        ["tips.reportAwesome" , true],
        ["tips.retractTip" , true],
        ["tips.tip" , true],
        ["tips.tipNew" , true],
        ["treasury.proposeSpend" , true],
        ["utility.asDerivative" , true],
        ["utility.batch" , true],
        ["utility.batchAll" , true],
        ["vesting.vestedTransfer" , true],
        ["xcmPallet.teleportAssets",true]
    ])
